# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: tests

on:
  workflow_dispatch:

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Get Code
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20

    - name: Setup Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: 3.12

    - name: Install Deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up environment variables
      run: |
          echo "USER=${{ secrets.USER }}" >> $GITHUB_ENV
          echo "PASS=${{ secrets.PASS }}" >> $GITHUB_ENV
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV
          echo "BROWSER=${{ secrets.BROWSER }}" >> $GITHUB_ENV
          echo "HEADLESS=${{ secrets.HEADLESS }}" >> $GITHUB_ENV

    - name: Browser Init
      run: rfbrowser init

    - name: Run Tests
      run: robot --listener RetryFailed -d ./logs tests/
